/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author wedad
 */
public class NewJFrameTimer extends javax.swing.JFrame {

    public static SwingWorker swing;
    public boolean on;
    public JFrame frame;
    javax.swing.Timer tim;

    String answer;
    int answer1;
    long difference;

    public NewJFrameTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        onTime = new javax.swing.JFormattedTextField();
        countD = new javax.swing.JTextField();
        chcolor = new javax.swing.JButton();
        boja = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        speed = new javax.swing.JComboBox();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timer");
        setBounds(new java.awt.Rectangle(700, 400, 0, 0));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("On Time");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Countdown (sec)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        onTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTimeActionPerformed(evt);
            }
        });

        countD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countDActionPerformed(evt);
            }
        });
        countD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countDKeyPressed(evt);
            }
        });

        chcolor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chcolor.setText("Choose Color");
        chcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bojaLayout = new javax.swing.GroupLayout(boja);
        boja.setLayout(bojaLayout);
        bojaLayout.setHorizontalGroup(
            bojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        bojaLayout.setVerticalGroup(
            bojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Speed");

        speed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        speed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        speed.setToolTipText("");
        speed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedActionPerformed(evt);
            }
        });

        start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        stop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop.setText("Stop");
        stop.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/timer1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sand.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("HH : mm : ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chcolor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(start)
                                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stop)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(onTime, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(countD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(onTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(countD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(boja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chcolor)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(stop))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        onTime.getAccessibleContext().setAccessibleName("HH:mm : ss");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            countD.setEnabled(true);
            onTime.setEnabled(false);
            jRadioButton1.setSelected(false);

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void onTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onTimeActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            onTime.setEnabled(true);
            countD.setEnabled(false);
            jRadioButton2.setSelected(false);

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void chcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcolorActionPerformed
        JColorChooser jcc = new JColorChooser();
        Color c = jcc.showDialog(null, "Color Chooser", Color.MAGENTA);
        boja.setBackground(c);
        boja.setVisible(true);
    }//GEN-LAST:event_chcolorActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed

        frame.hide();
        swing.cancel(true);

        boja.setEnabled(true);
        chcolor.setEnabled(true);
        countD.setEnabled(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        onTime.setEnabled(true);
        speed.setEnabled(true);
        start.setEnabled(true);
        stop.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Timer stopped!");


    }//GEN-LAST:event_stopActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        boja.setEnabled(false);
        chcolor.setEnabled(false);
        countD.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        onTime.setEnabled(false);
        speed.setEnabled(false);

        String sp = (String) speed.getSelectedItem();
        int spd = Integer.parseInt(sp);

        if (jRadioButton2.isSelected()) {
            answer = countD.getText();
            answer1 = Integer.parseInt(answer);

            swing = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {

                    tim = new javax.swing.Timer(answer1 * 1000, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {

                            boja.setEnabled(false);
                            chcolor.setEnabled(false);
                            countD.setEnabled(false);
                            jRadioButton1.setEnabled(false);
                            jRadioButton2.setEnabled(false);
                            onTime.setEnabled(false);
                            speed.setEnabled(false);

                            frame = new JFrame();
                            JLabel lb = new JLabel("TIMER STARTED");
                            frame.setSize(new Dimension(400, 400));
                            frame.add(lb);
                            frame.setLayout(new FlowLayout());
                            frame.setLocation(200, 400);

                            Color co = boja.getBackground();
                            frame.getContentPane().setBackground(co);

                            tim = new javax.swing.Timer(spd * 1000, new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {

                                    on = !on;
                                    if (!on) {
                                        frame.getContentPane().setBackground(Color.white);

                                    } else {
                                        frame.getContentPane().setBackground(co);
                                    }
                                }

                            });
                            tim.setRepeats(true);
                            tim.start();

                            frame.setVisible(true);
                        }

                    });
                    tim.start();
                    tim.setRepeats(false);

                    return null;
                }
            };
            swing.execute();
        } else if (jRadioButton1.isSelected()) {
            String time = onTime.getText();
            String timeSplit[] = time.split(":");
            int seconds = Integer.parseInt(timeSplit[0]) * 60 * 60
                    + Integer.parseInt(timeSplit[1]) * 60 + Integer.parseInt(timeSplit[2]) * 1000;

            swing = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {

                    Thread.sleep(difference);

                    tim = new javax.swing.Timer(seconds, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {

                            boja.setEnabled(false);
                            chcolor.setEnabled(false);
                            countD.setEnabled(false);
                            jRadioButton1.setEnabled(false);
                            jRadioButton2.setEnabled(false);
                            onTime.setEnabled(false);
                            speed.setEnabled(false);

                            frame = new JFrame();
                            JLabel lb = new JLabel("TIMER STARTED");

                            frame.setSize(new Dimension(400, 400));
                            frame.add(lb);

                            frame.setLayout(new FlowLayout());
                            frame.setLocation(200, 400);

                            Color col = boja.getBackground();
                            frame.getContentPane().setBackground(col);

                            tim = new javax.swing.Timer(spd * 1000, new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {

                                    on = !on;
                                    if (!on) {
                                        frame.getContentPane().setBackground(Color.white);

                                    } else {
                                        frame.getContentPane().setBackground(col);
                                    }

                                }

                            });
                            tim.setRepeats(true);
                            tim.start();
                            frame.setVisible(true);

                        }

                    });
                    tim.setRepeats(false);
                    tim.start();

                    return null;
                }

            };

            swing.execute();

        } else {
            JOptionPane.showMessageDialog(null, "You need to choose one of options!!!");
        }


    }//GEN-LAST:event_startActionPerformed

    private void speedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedActionPerformed

    private void countDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countDKeyPressed
        char ch = evt.getKeyChar();
        if (Character.isLetter(ch)) {
            countD.setText("");
            JOptionPane.showMessageDialog(null, "Only numbers allowed!");
        }
    }//GEN-LAST:event_countDKeyPressed

    private void countDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boja;
    private javax.swing.JButton chcolor;
    private javax.swing.JTextField countD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JFormattedTextField onTime;
    private javax.swing.JComboBox speed;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables

}
